### ISSUE TITLE
Output of the assembled layout

### ISSUE THREAD

**Issue by DeNIKE666** [dotswan/filament-grapesjs-v3#2]
Dear help me how now to output and display on a separate page assembled layout, I output the style is not correct, in my opinion not pulled tailwind styles, how can you fix this problem?

![Снимок экрана 2024-02-09 183727](https://github.com/dotswan/filament-grapesjs-v3/assets/30469085/2b5de747-3861-4076-bbcc-8d205f3c13d9)
![Снимок экрана 2024-02-09 183741](https://github.com/dotswan/filament-grapesjs-v3/assets/30469085/7863e2b9-e414-49af-907d-afe1de376dcd)
![Снимок экрана 2024-02-09 183756](https://github.com/dotswan/filament-grapesjs-v3/assets/30469085/b25a6b95-f319-47ea-a136-258710ff0c4f)
![Снимок экрана 2024-02-09 183812](https://github.com/dotswan/filament-grapesjs-v3/assets/30469085/64605c6d-b2d9-42a8-a22a-fd26753758d9)

Thanks for your help, handy library for building quick layouts.

**Comment by mohaphez** [comment]
Dear @DeNIKE666,

To load the template CSS correctly, there is no need to load the grapes.min.css and filament-grapesjs.css files. These files are meant for the editor's design and not for loading styles in the frontend.

To load CSS in the frontend, all you need to do is import Tailwind CSS from the CDN. This should make it work seamlessly.

![image](https://github.com/dotswan/filament-grapesjs-v3/assets/20874565/a2834bc3-ee1c-4b53-82bc-9282a3fd16c0)

![image](https://github.com/dotswan/filament-grapesjs-v3/assets/20874565/82a60102-5d31-4adb-b34a-7329822dc96a)
